name: currency_text_input_formatter
description: Currency Text Input Formatter for Flutter. Use it easy and simple for your flutter app.
version: 0.2.0
homepage: https://github.com/gtgalone/currency_text_input_formatter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.1


dev_dependencies:
  flutter_test:
    sdk: flutter
